### PR TITLE
added alternative numbers layout

### PR DESCRIPTION
**Pull request by ronniedroid**
Added an alternative numbers layout to shift to when in the symbols_shifted layout.
This is to easily enter phone numbers and other examples in notes, messages, etc..

I also changed the label for the symbols key to ?123 as I am using 123 for the numbers_alt

I also made sure that in this mode, the hitting space does not exit to KEYBOARD_LETTERS so that one can more conveniently enter phone numbers and such.

### CODE REVIEW

**Comment by naveensingh** [comment]
Thanks for the PR! Here are some suggestions:

  <br>



- I think Gboard does it better. Let's add a separate button for this layout on the original number layout and persist the selected number layout.
- The key to the right of "6" is empty and doesn't seem to do anything, a good candidate is "=".
- We should always show the ABC button even when the alternative number layout is selected. You can check Gboard for inspiration.

**Comment by ronniedroid** [comment]
@naveensingh can you see if you like the layout as is now or not, if not let me know what I should change.

I moved switching to the letters mode to it's own constant `KEYCODE_MODE_LETTERS = -3`

I added a new config option, lastSelectedMode to know to which mode to switch to when switching from the letters.

Made it so pressing space in the alt numbers mode will not switch you to the letters mode.

**Comment by ronniedroid** [comment]
Would be cool if we could change the key label between `123` and `?123` depending on `config.lastSelectedMode` in the letters mode.

**Comment by naveensingh** [comment]
Hey, I'll check this soon, probably later tonight.

**Comment by naveensingh** [comment]
I decided to disable the layout mode persistence for now, will re-enable when it is actually requested. Thanks!

**Pull request merged**
