### PR TITLE
added voice input button

### PR DESCRIPTION
**Pull request by ronniedroid**
Added a voice button to the toolbar

This can be disable or enabled by the user (Default is disabled)

### CODE REVIEW

**Comment by Aga-C** [comment]
Code structure has been already modified, so you can adjust your code in all PRs when you have time. Also, we decided to not copy English string over all languages, so it's easier for translators to keep track of untranslated strings.

**Comment by ronniedroid** [comment]
Should I remove the English strings?

**Comment by Aga-C** [comment]
Yes, please remove English strings from non-English languages.

**Comment by naveensingh** [comment]
@ronniedroid why are you closing your PRs? Too many conflicts?

**Pull request closed without merging**
