### PR TITLE
FEAT: added ability to toggle between selected languages

### PR DESCRIPTION
**Pull request by ronniedroid**
#### What is it?
- [ ] Bugfix
- [x] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR
- Added a toggle languages button between the emoji key and the space bar (In all languages layouts)
- Removed the comma key (as we can reach the comma by long pressing the period key)
- Moved the select language secondary key (popup) to the newly added toggle languages key
- Made sure the icon of the key is visible in light and dark themes (by applying appropriate colors)
- Implemented the functionality to toggle between the languages

#### Before/After Screenshots/Screen Record
- After:

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ronniedroid** [comment]
@naveensingh sorry I did not wait for the discussion  to be resolved, I had some time to spare today and decided to put this here in case you would like to merge it before the first release.  I added the toggle key at the bottom row, in case you want it in the toolbar instead of at the bottom row, let me know and I will move it there. best regards.

**Comment by Aga-C** [comment]
I think comma is a popular character, and we can't just remove its separate button. I haven't seen the keyboard without a comma button. Maybe you should do it similarly as it is in Gboard - emojis are moved to the comma long-press, so there's a place for language change button between comma and space bar.

**Comment by ronniedroid** [comment]
> I think comma is a popular character, and we can't just remove its separate button. I haven't seen the keyboard without a comma button. Maybe you should do it similarly as it is in Gboard - emojis are moved to the comma long-press, so there's a place for language change button between comma and space bar.

The AOSP keyboard doesn't have a dedicated comma key, but your idea also sounds good, should I do that?

**Comment by Aga-C** [comment]
I don't know, you may try if you like. If I were you, I'd wait a bit, maybe Naveen will give his opinion soon.

**Comment by ronniedroid** [comment]
I just noticed that I have put the button to the left of the emoji key and not the right 😅, will fix later.

**Comment by naveensingh** [comment]
Closing because https://github.com/FossifyOrg/Keyboard/discussions/25#discussioncomment-9561990

**Pull request closed without merging**
